name: illuminerf_results
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - pytorch::pytorch=2.4.0
  - pytorch::torchaudio=2.4.0
  - pytorch::torchvision=0.19.0
  - pytorch::pytorch-cuda=11.8
  - scikit-image=0.24.0
  - jupyterlab=4.2.5
  - matplotlib=3.9.2
  - numpy=2.1.2
  - scipy=1.14.1
  - pillow=10.4.0
  - setuptools=75.1.0
  - tqdm=4.66.5
  - pip=24.2
  - pip:
      - joblib==1.4.2
      - lpips==0.1.4
